spring:
  application:
    name: gateway-server
  cloud:
    discovery:
      enabled: true
    gateway:
      gdefault-filters:
        - DebupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfiguration:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowrdHeaders: "*"
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/*/auth/**

        - id: ms-products
          uri: lb://ms-products
          predicates:
            - Path=/api/*/products/**

        - id: ms-orders
          uri: lb://ms-orders
          predicates:
            - Path=/api/*/orders/**, /api/*/cart/**
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 5555

jwt:
  secret: wperdjklfxcsdjfoaqeasdlasdxzwetpsadz

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
