server:
  port: 8180

spring:
  application:
    name: ms-auth

jwt:
  secret: wperdjklfxcsdjfoaqeasdlasdxzwetpsadz

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}